fix husky

diff --git a/frontend/.husky/pre-push b/frontend/.husky/pre-push
--- a/frontend/.husky/pre-push
+++ b/frontend/.husky/pre-push
@@ -1,2 +1,6 @@
 cd "$(dirname "$0")/../"
 pnpm test
+if [ $? -ne 0 ]; then
+  echo "Tests failed. Push aborted."
+  exit 1
+fi
